import type { Lang, WordTheme } from '../types.js'
import { WORDS_EN } from './en.js'
import { WORDS_SV } from './sv.js'

/** Extra words for themed packs (merged with base or used as primary set). */
const FEST_SV = WORDS_SV
const FEST_EN = WORDS_EN

const FAMILJ_SV = [
  'glass',
  'ballong',
  'kanin',
  'panda',
  'cykel',
  'regnbåge',
  'snögubbe',
  'badanka',
  'julgran',
  'pizza',
  'banan',
  'lejon',
  'pingvin',
  'koala',
  'fjäril',
  'äpple',
  'dinosaurier',
  'raket',
  'cirkus',
  'godis',
  'jordgubbe',
  'superhjälte',
  'trädhus',
  'badboll',
  'musikfestival',
  'chokladmjölk',
  'liten robot',
  'fotboll',
  'paraply',
  'kamera',
  'solros',
  'tåg',
  'uggla',
  'kaktus',
  'gitarr',
  'slott',
  'elefant',
  'måne',
  'trampolin',
  'popcorn',
  'fyr',
  'zebra',
  'ananas',
  'sköldpadda',
  'igelkott',
  'sandwich',
  'känguru',
  'nyckel',
  'sandslott',
  'camping',
  'motorcykel',
  'norrsken',
  'röd tulpan',
  'strandstol',
  'bibliotek',
  'tandborste',
  'astronaut',
  'drake',
  'pirat',
  'robot',
  'spöke',
  'brandbil',
  'helikopter',
  'teleskop',
  'haj',
  'bläckfisk',
  'skridskor',
  'trumpet',
  'vulkan',
  'taxi',
  'hammare',
  'tunnelbana',
  'ninja',
  'hotell',
  'mikrofon',
  'flodhäst',
  'ryggsäck',
  'bergstopp',
  'trollkarl',
  'skattkista',
  'morgonkaffe',
  'pizzaslice',
  'tidning',
  'gul taxi',
]

const FAMILJ_EN = [
  'ice cream',
  'balloon',
  'rabbit',
  'panda',
  'bicycle',
  'rainbow',
  'snowman',
  'rubber duck',
  'christmas tree',
  'pizza',
  'banana',
  'lion',
  'penguin',
  'koala',
  'butterfly',
  'apple',
  'dinosaur',
  'rocket',
  'circus',
  'candy',
  'strawberry',
  'superhero',
  'treehouse',
  'beach ball',
  'music festival',
  'chocolate milk',
  'tiny robot',
  'soccer',
  'umbrella',
  'camera',
  'sunflower',
  'train',
  'owl',
  'cactus',
  'guitar',
  'castle',
  'elephant',
  'moon',
  'trampoline',
  'popcorn',
  'lighthouse',
  'zebra',
  'pineapple',
  'turtle',
  'hedgehog',
  'sandwich',
  'kangaroo',
  'key',
  'sandcastle',
  'camping',
  'motorcycle',
  'northern lights',
  'red tulip',
  'beach chair',
  'library',
  'toothbrush',
  'astronaut',
  'dragon',
  'pirate',
  'robot',
  'ghost',
  'fire truck',
  'helicopter',
  'telescope',
  'shark',
  'octopus',
  'ice skates',
  'trumpet',
  'volcano',
  'taxi',
  'hammer',
  'subway',
  'ninja',
  'hotel',
  'microphone',
  'hippo',
  'backpack',
  'mountain peak',
  'wizard',
  'treasure chest',
  'morning coffee',
  'pizza slice',
  'newspaper',
  'yellow taxi',
]

const JOBB_SV = [
  'möte',
  'powerpoint',
  'deadline',
  'kaffe',
  'skrivare',
  'lunchlåda',
  'teams-möte',
  'höj-sänk-bord',
  'namnskylt',
  'fikapaus',
  'lönebesked',
  'whiteboard',
  'post-it',
  'kopieringsmaskin',
  'kontorsstol',
  'headset',
  'kalenderinbjudan',
  'statusuppdatering',
  'brainstorm',
  'projektor',
  'hisspitch',
  'övertid',
  'korridor',
  'nyckelbricka',
  'kafeteria',
  'årsmöte',
  'budget',
  'kpi',
  'onboarding',
  'remote-dag',
  'slack-notis',
  'mejltråd',
  'chef',
  'praktikant',
  'exportfil',
  'excel',
  'måndagsmöte',
  'fredagsöl',
  'tågpendlare',
  'parkering',
  'visitkort',
  'konferensrum',
  'zoom-bakgrund',
  'mute-knapp',
  'skärmdelning',
  'agenda',
  'protokoll',
  'semesteransökan',
  'kassaskåp',
  'reception',
  'brandövning',
  'kaffemaskin',
  'mjölk i kyl',
  'stämpelklocka',
  'personalrum',
  'laddkabel',
  'usb-minne',
  'skrivbordslampa',
  'pärm',
  'arkiv',
  'kvartalsrapport',
  'kundmöte',
  'offert',
  'faktura',
  'signatur',
  'avtal',
  'hänglås',
  'skolväska till kontoret',
  'gymväska',
  'cykelställ',
  'regnponcho',
  'thermos',
  'bullet journal',
  'kanban-tavla',
  'standup',
  'sprint',
  'retro',
  'demo',
  'bugg',
  'hotfix',
  'deploy',
  'vpn',
  'lösenord',
  'tvåfaktorskod',
  'skrivbordsväxt',
  'ljudisolering',
  'open space',
  'hörlurar',
  'tyst rum',
  'printerpapper',
  'häftapparat',
]

const JOBB_EN = [
  'meeting',
  'powerpoint',
  'deadline',
  'coffee',
  'printer',
  'lunchbox',
  'teams call',
  'standing desk',
  'name badge',
  'coffee break',
  'payslip',
  'whiteboard',
  'post-it',
  'copier',
  'office chair',
  'headset',
  'calendar invite',
  'status update',
  'brainstorm',
  'projector',
  'elevator pitch',
  'overtime',
  'hallway',
  'keycard',
  'cafeteria',
  'all-hands',
  'budget',
  'kpi',
  'onboarding',
  'remote day',
  'slack ping',
  'email thread',
  'boss',
  'intern',
  'export file',
  'excel',
  'monday meeting',
  'friday beers',
  'commuter',
  'parking',
  'business card',
  'conference room',
  'zoom background',
  'mute button',
  'screen share',
  'agenda',
  'minutes',
  'pto request',
  'safe',
  'reception',
  'fire drill',
  'coffee machine',
  'milk in fridge',
  'time clock',
  'break room',
  'charger cable',
  'usb stick',
  'desk lamp',
  'binder',
  'archive',
  'quarterly report',
  'client meeting',
  'quote',
  'invoice',
  'signature',
  'contract',
  'padlock',
  'office backpack',
  'gym bag',
  'bike rack',
  'rain poncho',
  'thermos',
  'bullet journal',
  'kanban board',
  'standup',
  'sprint',
  'retro',
  'demo',
  'bug',
  'hotfix',
  'deploy',
  'vpn',
  'password',
  '2fa code',
  'desk plant',
  'noise canceling',
  'open office',
  'headphones',
  'quiet room',
  'printer paper',
  'stapler',
]

const ADULT_SV = [
  ...WORDS_SV.slice(0, 40),
  'afterwork',
  'shotglass',
  'häng',
  'ex',
  'dejt',
  'svartsjuka',
  'flört',
  'one-night',
  'tinder-match',
  'walk of shame',
  'hänglås på dörren',
  'sena sms',
  'festnatt',
  'bakfylla',
  'shot-roulette',
  'sanning eller konsekvens',
  'kyss',
  'romans',
  'otrohet',
  'hemlig beundrare',
  'striptease-låda',
  'handbojor',
  'massageolja',
  'hotellrum',
  'minibar',
  'bubbel',
  'nattklubb',
  'vip-lounge',
  'pickup-line',
  'ghosting',
  'situationship',
  'friends with benefits',
  'jealousy text',
  'låtsasdejt',
  'bröllopsnatt',
  'smekmånad',
  'sexig halloween',
  'body shot',
  'pole dance',
  'låtsasbråk',
  'makeout',
  'netflix and chill',
  'red flag',
  'green flag',
  'booty call',
  'kinky',
  'safe word',
  'blinddejt',
  'speed dating',
  'afterparty',
  'club toilet',
  'stolen jacket',
  'lost phone',
  'uber home',
  'walk of pride',
]

const ADULT_EN = [
  ...WORDS_EN.slice(0, 40),
  'afterwork',
  'shot glass',
  'hookup',
  'ex',
  'date night',
  'jealousy',
  'flirt',
  'one-night stand',
  'tinder match',
  'walk of shame',
  'do not disturb',
  'late texts',
  'party night',
  'hangover',
  'shot roulette',
  'truth or dare',
  'kiss',
  'romance',
  'cheating',
  'secret admirer',
  'striptease box',
  'handcuffs',
  'massage oil',
  'hotel room',
  'minibar',
  'bubbly',
  'nightclub',
  'vip lounge',
  'pickup line',
  'ghosting',
  'situationship',
  'friends with benefits',
  'jealousy text',
  'fake date',
  'wedding night',
  'honeymoon',
  'sexy halloween',
  'body shot',
  'pole dance',
  'fake fight',
  'makeout',
  'netflix and chill',
  'red flag',
  'green flag',
  'booty call',
  'kinky',
  'safe word',
  'blind date',
  'speed dating',
  'afterparty',
  'club bathroom',
  'stolen jacket',
  'lost phone',
  'uber home',
  'walk of pride',
]

const PACKS: Record<WordTheme, { sv: string[]; en: string[] }> = {
  fest: { sv: FEST_SV, en: FEST_EN },
  familj: { sv: FAMILJ_SV, en: FAMILJ_EN },
  jobb: { sv: JOBB_SV, en: JOBB_EN },
  adult: { sv: ADULT_SV, en: ADULT_EN },
}

export function wordPack(lang: Lang, theme: WordTheme = 'fest'): string[] {
  const pack = PACKS[theme] ?? PACKS.fest
  return lang === 'en' ? pack.en : pack.sv
}

export function freeWordPack(lang: Lang, theme: WordTheme = 'fest'): string[] {
  return wordPack(lang, theme).slice(0, 60)
}
